### ISSUE TITLE
Memory leak

### ISSUE THREAD

**Issue by srgbtl** [StMarian/ListOnPointers#1]
```
int main()
{
        char** list;
        ListInit(&list);
        ListInit(&list);

        ListDestroy(&list);

        return 0;
}
```

**Comment by StMarian** [comment]
Solved by https://github.com/StMarian/ListOnPointers/commit/adcfafff12811f9da49ed518342475e95ddf48cb

**Comment by StMarian** [comment]
Solved by https://github.com/StMarian/ListOnPointers/commit/974ad12f2ab492eb6917b84de70642158e18fa64
